import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author paolo
 */
public class BancaGUI extends javax.swing.JFrame {
    private Banca banca;

    /**
     * Creates new form BancaGUI
     */
    public BancaGUI(Banca banca) {
        this.banca = banca;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prelevaButton = new javax.swing.JButton();
        depositaButton = new javax.swing.JButton();
        esciButton = new javax.swing.JButton();
        informazioniUtente = new javax.swing.JPanel();
        nomeLabel = new javax.swing.JLabel();
        cognomeLabel = new javax.swing.JLabel();
        saldoLabel = new javax.swing.JLabel();
        ibanLabel = new javax.swing.JLabel();
        storicoEntrateButton = new javax.swing.JButton();
        storicoUsciteButton1 = new javax.swing.JButton();
        cambioIntestatarioButton = new javax.swing.JButton();
        bonificoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        prelevaButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        prelevaButton.setText("PRELEVA DENARO");
        prelevaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prelevaButtonActionPerformed(evt);
            }
        });

        depositaButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        depositaButton.setText("VERSA DENARO");
        depositaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositaButtonActionPerformed(evt);
            }
        });

        esciButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        esciButton.setText("ESCI");
        esciButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esciButtonActionPerformed(evt);
            }
        });

        informazioniUtente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informazioni", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16))); // NOI18N

        nomeLabel.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        nomeLabel.setText("Nome: " + banca.getNome());

        cognomeLabel.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        cognomeLabel.setText("Cognome: " + banca.getCognome());

        saldoLabel.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        saldoLabel.setText("Saldo: " + banca.getSaldo());

        ibanLabel.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        ibanLabel.setText("IBAN: " + banca.getIban());

        storicoEntrateButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        storicoEntrateButton.setText("STORICO ENTRATE");
        storicoEntrateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storicoEntrateButtonActionPerformed(evt);
            }
        });

        storicoUsciteButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        storicoUsciteButton1.setText("STORICO USCITE");
        storicoUsciteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storicoUsciteButton1ActionPerformed(evt);
            }
        });

        cambioIntestatarioButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cambioIntestatarioButton.setText("CAMBIO INTESTATARIO");
        cambioIntestatarioButton.setMaximumSize(new java.awt.Dimension(172, 32));
        cambioIntestatarioButton.setMinimumSize(new java.awt.Dimension(172, 32));
        cambioIntestatarioButton.setPreferredSize(new java.awt.Dimension(344, 32));
        cambioIntestatarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambioIntestatarioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout informazioniUtenteLayout = new javax.swing.GroupLayout(informazioniUtente);
        informazioniUtente.setLayout(informazioniUtenteLayout);
        informazioniUtenteLayout.setHorizontalGroup(
            informazioniUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informazioniUtenteLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(informazioniUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(informazioniUtenteLayout.createSequentialGroup()
                        .addGroup(informazioniUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeLabel)
                            .addComponent(cognomeLabel))
                        .addGap(195, 195, 195)
                        .addComponent(storicoUsciteButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(storicoEntrateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(informazioniUtenteLayout.createSequentialGroup()
                        .addGroup(informazioniUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ibanLabel)
                            .addGroup(informazioniUtenteLayout.createSequentialGroup()
                                .addComponent(saldoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cambioIntestatarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(106, 106, 106))))
        );
        informazioniUtenteLayout.setVerticalGroup(
            informazioniUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informazioniUtenteLayout.createSequentialGroup()
                .addGroup(informazioniUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informazioniUtenteLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(informazioniUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(storicoEntrateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(storicoUsciteButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(informazioniUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saldoLabel)
                            .addComponent(cambioIntestatarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(ibanLabel))
                    .addGroup(informazioniUtenteLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(nomeLabel)
                        .addGap(30, 30, 30)
                        .addComponent(cognomeLabel)))
                .addGap(40, 40, 40))
        );

        bonificoButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bonificoButton.setText("BONIFICO");
        bonificoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonificoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(depositaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bonificoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(227, 227, 227)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prelevaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(esciButton, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(informazioniUtente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(informazioniUtente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prelevaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bonificoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esciButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prelevaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prelevaButtonActionPerformed
        Preleva preleva = new Preleva(this, true, banca.getSaldo());
        preleva.setVisible(true);
        if (preleva.prelievo != 0) {
            if(banca.prelievo(preleva.prelievo)) {
                JOptionPane.showMessageDialog(this, "Versamento effettuato con successo", "Versamento", JOptionPane.INFORMATION_MESSAGE);
                saldoLabel.setText("Saldo: " + banca.getSaldo() + "€");
            } else {
                JOptionPane.showMessageDialog(this, "Errore durante il versamento", "Versamento", JOptionPane.ERROR_MESSAGE);
            }
            saldoLabel.setText("Saldo: " + banca.getSaldo() + "€");
        }
    }//GEN-LAST:event_prelevaButtonActionPerformed

    private void depositaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositaButtonActionPerformed
        Versamento deposita = new Versamento(this, true);
        deposita.setVisible(true);
        if (deposita.versamento != 0) {
            if(banca.versamento(deposita.versamento)) {
                JOptionPane.showMessageDialog(this, "Versamento effettuato con successo", "Versamento", JOptionPane.INFORMATION_MESSAGE);
                saldoLabel.setText("Saldo: " + banca.getSaldo() + "€");
            } else {
                JOptionPane.showMessageDialog(this, "Errore durante il versamento", "Versamento", JOptionPane.ERROR_MESSAGE);
            }
            saldoLabel.setText("Saldo: " + banca.getSaldo() + "€");
        }
    }//GEN-LAST:event_depositaButtonActionPerformed

    private void esciButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esciButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_esciButtonActionPerformed

    private void bonificoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonificoButtonActionPerformed
        Bonifico bonifico = new Bonifico(this, true, banca.getSaldo(), banca.getIban());
        bonifico.setVisible(true);
        if (bonifico.quantita != 0) {
            int result = banca.bonifico(bonifico.ibanRicevente, bonifico.quantita);
            if(result == 0) {
                JOptionPane.showMessageDialog(this, "Bonifico effettuato con successo", "Bonifico", JOptionPane.INFORMATION_MESSAGE);
                saldoLabel.setText("Saldo: " + banca.getSaldo() + "€");
            } else if(result == 1) {
                JOptionPane.showMessageDialog(this, "Non hai abbastanza soldi!", "Bonifico", JOptionPane.ERROR_MESSAGE);
            } else if(result == 2) {
                JOptionPane.showMessageDialog(this, "L'iban inserito non è valido!", "Bonifico", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Errore durante il bonifico", "Bonifico", JOptionPane.ERROR_MESSAGE);
            }
            saldoLabel.setText("Saldo: " + banca.getSaldo() + "€");
        }
    }//GEN-LAST:event_bonificoButtonActionPerformed

    private void storicoEntrateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storicoEntrateButtonActionPerformed
        Entrate entrate = new Entrate(this, true, banca.getEntrate());
        entrate.setResizable(false);
        entrate.setVisible(true);
    }//GEN-LAST:event_storicoEntrateButtonActionPerformed

    private void storicoUsciteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storicoUsciteButton1ActionPerformed
        Uscite uscite = new Uscite(this, true, banca.getUscite());
        uscite.setResizable(false);
        uscite.setVisible(true);
    }//GEN-LAST:event_storicoUsciteButton1ActionPerformed

    private void cambioIntestatarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambioIntestatarioButtonActionPerformed
        CambioIntestatario cambioIntestatario = new CambioIntestatario(this, true, banca.getNome(), banca.getCognome());
        cambioIntestatario.setVisible(true);
        if(cambioIntestatario.nome == banca.getNome() || cambioIntestatario.cognome == banca.getCognome()) return;
        else if(banca.cambioIntestatario(cambioIntestatario.nome, cambioIntestatario.cognome)) {
            nomeLabel.setText("Nome: " + banca.getNome());
            cognomeLabel.setText("Cognome: " + banca.getCognome());
            this.pack();
            JOptionPane.showMessageDialog(this, "Cambio intestatario effettuato con successo", "Cambio intestatario", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Cambio intestatario non effettuato, riprova più tardi", "Cambio intestatario", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cambioIntestatarioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BancaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BancaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BancaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BancaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BancaGUI(new Banca()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bonificoButton;
    private javax.swing.JButton cambioIntestatarioButton;
    private javax.swing.JLabel cognomeLabel;
    private javax.swing.JButton depositaButton;
    private javax.swing.JButton esciButton;
    private javax.swing.JLabel ibanLabel;
    private javax.swing.JPanel informazioniUtente;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JButton prelevaButton;
    private javax.swing.JLabel saldoLabel;
    private javax.swing.JButton storicoEntrateButton;
    private javax.swing.JButton storicoUsciteButton1;
    // End of variables declaration//GEN-END:variables
}
