import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author paolo
 */
public class CambioIntestatario extends javax.swing.JDialog {
    public String nome, cognome;

    /**
     * Creates new form cambioIntestatario
     */
    public CambioIntestatario(java.awt.Frame parent, boolean modal, String nome, String cognome) {
        super(parent, modal);
        this.nome = nome;
        this.cognome = cognome;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        annullaButton = new javax.swing.JButton();
        confermaButton = new javax.swing.JButton();
        nuovoCognomeField = new javax.swing.JTextField();
        nuovoNomeField = new javax.swing.JTextField();
        nuovoNomeLabel = new javax.swing.JLabel();
        nuovoCognomeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        annullaButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        annullaButton.setText("ANNULLA");
        annullaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annullaButtonActionPerformed(evt);
            }
        });

        confermaButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confermaButton.setText("CONFERMA");
        confermaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confermaButtonActionPerformed(evt);
            }
        });

        nuovoCognomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuovoCognomeFieldActionPerformed(evt);
            }
        });
        nuovoCognomeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nuovoCognomeFieldKeyPressed(evt);
            }
        });

        nuovoNomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuovoNomeFieldActionPerformed(evt);
            }
        });
        nuovoNomeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nuovoNomeFieldKeyPressed(evt);
            }
        });

        nuovoNomeLabel.setText("Nuovo Nome");

        nuovoCognomeLabel.setText("Nuovo Cognome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nuovoCognomeField)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(annullaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(107, 107, 107)
                            .addComponent(confermaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(nuovoNomeField))
                    .addComponent(nuovoNomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuovoCognomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nuovoNomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuovoNomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuovoCognomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuovoCognomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confermaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annullaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annullaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annullaButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_annullaButtonActionPerformed

    private void confermaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confermaButtonActionPerformed
        if(nuovoNomeField.getText().equals("") || nuovoCognomeField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Compila tutti i campi!");
        } else if(nuovoNomeField.getText().equals(this.nome) && nuovoCognomeField.getText().equals(this.cognome)){
            JOptionPane.showMessageDialog(null, "Non hai cambiato nessun valore!");
        } else {
            this.nome = nuovoNomeField.getText();
            this.cognome = nuovoCognomeField.getText();
            this.dispose();
        }
    }//GEN-LAST:event_confermaButtonActionPerformed

    private void nuovoCognomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuovoCognomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuovoCognomeFieldActionPerformed

    private void nuovoNomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuovoNomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuovoNomeFieldActionPerformed

    private void nuovoNomeFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nuovoNomeFieldKeyPressed
        if(evt.getKeyCode() == evt.VK_TAB || evt.getKeyCode() == evt.VK_ENTER){
            nuovoCognomeField.requestFocus();
        }
    }//GEN-LAST:event_nuovoNomeFieldKeyPressed

    private void nuovoCognomeFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nuovoCognomeFieldKeyPressed
        if(evt.getKeyCode() == evt.VK_TAB || evt.getKeyCode() == evt.VK_ENTER){
            confermaButton.doClick();
        }
    }//GEN-LAST:event_nuovoCognomeFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioIntestatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioIntestatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioIntestatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioIntestatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CambioIntestatario dialog = new CambioIntestatario(new javax.swing.JFrame(), true, "", "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annullaButton;
    private javax.swing.JButton confermaButton;
    private javax.swing.JTextField nuovoCognomeField;
    private javax.swing.JLabel nuovoCognomeLabel;
    private javax.swing.JTextField nuovoNomeField;
    private javax.swing.JLabel nuovoNomeLabel;
    // End of variables declaration//GEN-END:variables
}
