/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author paolo
 */
import java.util.*;
public class Entrate extends javax.swing.JDialog {
    private Map<String, Double> entrate = new HashMap<String, Double>();

    /**
     * Creates new form Uscite
     */
    public Entrate(java.awt.Frame parent, boolean modal, String entrate) {
        super(parent, modal);
        if(entrate != "") {
            String[] coppie = entrate.substring(1,entrate.length() - 1).split(", ");
            for (int i=0; i<coppie.length; i++) {
                String coppia = coppie[i];
                String[] chiaveValore = coppia.split("=");
                this.entrate.put(chiaveValore[0], Double.parseDouble(chiaveValore[1]));
            }
        } else {
            this.entrate = null;
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        usciteTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        usciteTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane1.setViewportView(usciteTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        String[] columnNames = {"Tipo", "IBAN (in caso di bonifico)", "Importo", "Data"};
        if(entrate != null) {
            Object[][] data = new Object[entrate.size()][4];
            int i = 0;
            for (Map.Entry<String, Double> entry : entrate.entrySet()) {
                String[] entryKeySlitted = entry.getKey().split("/");
                if(entryKeySlitted[0].equals("versamento")) {
                    data[i][0] = "Versamento";
                    data[i][2] = "";
                    data[i][2] = entry.getValue() + "€";
                    data[i][3] = entryKeySlitted[1] + " " + entryKeySlitted[2];
                } else {
                    data[i][0] = "Bonifico";
                    data[i][1] = entryKeySlitted[0];
                    data[i][2] = entry.getValue() + "€";
                    data[i][3] = entryKeySlitted[1] + " " + entryKeySlitted[2];
                }
                i++;
            }
            usciteTable.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));
        } else {
            Object[][] data = new Object[1][4];
            data[0][0] = "Nessuna entrata";
            usciteTable.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uscite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uscite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uscite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uscite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Uscite dialog = new Uscite(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable usciteTable;
    // End of variables declaration//GEN-END:variables
}
